# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      pip3 install --upgrade pip setuptools wheel
      pip3 install --only-binary=numpy,scipy numpy scipy
      pip3 install cython
      pip3 install .
    displayName: 'Installing scikit-multiflow'

  - script: |
      pip install pytest
      pip install codecov
      pip install pytest-cov
      pytest tests --showlocals -v --cov=skmultiflow
    displayName: 'Running tests'
